name: Python package

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
          uses: actions/checkout@v2
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          docker-compose run --rm app sh -c "flake8"

      - name: Test with pytest
        run: |
          docker-compose run --rm app sh -c "pytes"